### ISSUE TITLE
403 forbidden IP

### ISSUE THREAD

**Issue by lintdeveloper** [Gandi/bridge-utils#3]
When I want to install bridge-utils on my raspberry pi I always get forbidden IP error. How do I resolve this?

**Comment by ghost** [comment]
I think yo should elaborate a little bit more your question, like What's the exact error message? or Wich step you used to set up the bridge?

**Comment by lintdeveloper** [comment]
Error resolved, the IP address I was connected to was limiting me from downloading the package. Thanks alot
